//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 12:14:05 PM PST 
//


package cohdemoeditor.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for launcher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="launcher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="disable2d" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fullscreen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fps" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="resolutionX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="resolutionY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "launcher", propOrder = {
    "disable2D",
    "fullscreen",
    "fps",
    "resolutionX",
    "resolutionY",
    "mode"
})
public class Launcher {

    @XmlElement(name = "disable2d")
    protected boolean disable2D;
    protected boolean fullscreen;
    protected Integer fps;
    protected Integer resolutionX;
    protected Integer resolutionY;
    protected int mode;

    /**
     * Gets the value of the disable2D property.
     * 
     */
    public boolean isDisable2D() {
        return disable2D;
    }

    /**
     * Sets the value of the disable2D property.
     * 
     */
    public void setDisable2D(boolean value) {
        this.disable2D = value;
    }

    /**
     * Gets the value of the fullscreen property.
     * 
     */
    public boolean isFullscreen() {
        return fullscreen;
    }

    /**
     * Sets the value of the fullscreen property.
     * 
     */
    public void setFullscreen(boolean value) {
        this.fullscreen = value;
    }

    /**
     * Gets the value of the fps property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFps() {
        return fps;
    }

    /**
     * Sets the value of the fps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFps(Integer value) {
        this.fps = value;
    }

    /**
     * Gets the value of the resolutionX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResolutionX() {
        return resolutionX;
    }

    /**
     * Sets the value of the resolutionX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResolutionX(Integer value) {
        this.resolutionX = value;
    }

    /**
     * Gets the value of the resolutionY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResolutionY() {
        return resolutionY;
    }

    /**
     * Sets the value of the resolutionY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResolutionY(Integer value) {
        this.resolutionY = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     */
    public int getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     */
    public void setMode(int value) {
        this.mode = value;
    }

}
