//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 12:14:05 PM PST 
//


package cohdemoeditor.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timerange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timerange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="starttime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timerange", propOrder = {
    "starttime",
    "endtime"
})
public class Timerange {

    protected int starttime;
    protected int endtime;

    /**
     * Gets the value of the starttime property.
     * 
     */
    public int getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     */
    public void setStarttime(int value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the endtime property.
     * 
     */
    public int getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     */
    public void setEndtime(int value) {
        this.endtime = value;
    }

}
