/*
 * InterpolatorPanelParametric.java
 *
 * Created on July 27, 2007, 11:02 PM
 */

package cohdemoeditor.wizards;

import java.awt.*;

/**
 * This panel provides a user interface for parametric interpolation. Currently,
 * it just displays a message requesting the user to use the AutoPOSWizard
 * instead.
 * 
 * @author Darren Lee
 */
@SuppressWarnings("serial")
public class InterpolatorPanelParametric extends javax.swing.JPanel {

	/** Creates new form InterpolatorPanelParametric */
	public InterpolatorPanelParametric(Dialog parent) {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		northLabel = new javax.swing.JLabel();
		tempMessageTextArea = new javax.swing.JTextArea();

		setLayout(new java.awt.BorderLayout());

		northLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
		northLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		northLabel.setText("Parametric Interpolation");
		northLabel.setBorder(new javax.swing.border.EmptyBorder(
				new java.awt.Insets(5, 5, 5, 5)));
		add(northLabel, java.awt.BorderLayout.NORTH);

		tempMessageTextArea.setEditable(false);
		tempMessageTextArea.setLineWrap(true);
		tempMessageTextArea.setRows(8);
		tempMessageTextArea
				.setText("The parametric interpolator is currently implemented as the separate \"Generate POS by formula\" wizard.  That wizard will be moved here in a future version of the program.");
		tempMessageTextArea.setWrapStyleWord(true);
		tempMessageTextArea.setMinimumSize(new java.awt.Dimension(100, 500));
		add(tempMessageTextArea, java.awt.BorderLayout.CENTER);

	}

	// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel northLabel;
	private javax.swing.JTextArea tempMessageTextArea;
	// End of variables declaration//GEN-END:variables

}
