//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 12:14:05 PM PST 
//


package cohdemoeditor.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DemoEditorConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DemoEditorConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="default-demo-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="default-x-pos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="default-y-pos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="default-coh-path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pc" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wizard" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filterlists" type="{http://xml.netbeans.org/examples/targetNS}filterlist" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="launcher" type="{http://xml.netbeans.org/examples/targetNS}launcher" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DemoEditorConfigType", propOrder = {
    "version",
    "defaultDemoPath",
    "defaultXPos",
    "defaultYPos",
    "width",
    "height",
    "defaultCohPath",
    "pc",
    "wizard",
    "filterlists",
    "launcher"
})
public class DemoEditorConfigType {

    @XmlElement(required = true)
    protected String version;
    @XmlElement(name = "default-demo-path", required = true)
    protected String defaultDemoPath;
    @XmlElement(name = "default-x-pos")
    protected int defaultXPos;
    @XmlElement(name = "default-y-pos")
    protected int defaultYPos;
    protected int width;
    protected int height;
    @XmlElement(name = "default-coh-path", required = true)
    protected String defaultCohPath;
    protected boolean pc;
    protected List<String> wizard;
    protected List<Filterlist> filterlists;
    protected Launcher launcher;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the defaultDemoPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDemoPath() {
        return defaultDemoPath;
    }

    /**
     * Sets the value of the defaultDemoPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDemoPath(String value) {
        this.defaultDemoPath = value;
    }

    /**
     * Gets the value of the defaultXPos property.
     * 
     */
    public int getDefaultXPos() {
        return defaultXPos;
    }

    /**
     * Sets the value of the defaultXPos property.
     * 
     */
    public void setDefaultXPos(int value) {
        this.defaultXPos = value;
    }

    /**
     * Gets the value of the defaultYPos property.
     * 
     */
    public int getDefaultYPos() {
        return defaultYPos;
    }

    /**
     * Sets the value of the defaultYPos property.
     * 
     */
    public void setDefaultYPos(int value) {
        this.defaultYPos = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the defaultCohPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCohPath() {
        return defaultCohPath;
    }

    /**
     * Sets the value of the defaultCohPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCohPath(String value) {
        this.defaultCohPath = value;
    }

    /**
     * Gets the value of the pc property.
     * 
     */
    public boolean isPc() {
        return pc;
    }

    /**
     * Sets the value of the pc property.
     * 
     */
    public void setPc(boolean value) {
        this.pc = value;
    }

    /**
     * Gets the value of the wizard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wizard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWizard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWizard() {
        if (wizard == null) {
            wizard = new ArrayList<String>();
        }
        return this.wizard;
    }

    /**
     * Gets the value of the filterlists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterlists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterlists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Filterlist }
     * 
     * 
     */
    public List<Filterlist> getFilterlists() {
        if (filterlists == null) {
            filterlists = new ArrayList<Filterlist>();
        }
        return this.filterlists;
    }

    /**
     * Gets the value of the launcher property.
     * 
     * @return
     *     possible object is
     *     {@link Launcher }
     *     
     */
    public Launcher getLauncher() {
        return launcher;
    }

    /**
     * Sets the value of the launcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Launcher }
     *     
     */
    public void setLauncher(Launcher value) {
        this.launcher = value;
    }

}
