//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 12:14:05 PM PST 
//


package cohdemoeditor.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cohdemoeditor.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DemoEditorConfig_QNAME = new QName("http://xml.netbeans.org/examples/targetNS", "demo-editor-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cohdemoeditor.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DemoEditorConfigType }
     * 
     */
    public DemoEditorConfigType createDemoEditorConfigType() {
        return new DemoEditorConfigType();
    }

    /**
     * Create an instance of {@link Launcher }
     * 
     */
    public Launcher createLauncher() {
        return new Launcher();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Timerange }
     * 
     */
    public Timerange createTimerange() {
        return new Timerange();
    }

    /**
     * Create an instance of {@link Filterlist }
     * 
     */
    public Filterlist createFilterlist() {
        return new Filterlist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DemoEditorConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/examples/targetNS", name = "demo-editor-config")
    public JAXBElement<DemoEditorConfigType> createDemoEditorConfig(DemoEditorConfigType value) {
        return new JAXBElement<DemoEditorConfigType>(_DemoEditorConfig_QNAME, DemoEditorConfigType.class, null, value);
    }

}
