//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.11 at 12:14:05 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/examples/targetNS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cohdemoeditor.config;
