/*
 * DemoWizardChooser.java
 *
 * Created on June 17, 2005, 9:42 AM
 */

package cohdemoeditor.swing;

import javax.swing.*;

import cohdemoeditor.DemoWizardManager;

/**
 * A DemoWizardChooser provides a user interface for the user to select a wizard
 * to run. It's basically just a dialog containing a list of wizards and buttons
 * for run, cancel, load, and about (which displays the wizard's description)
 * 
 * @author Darren Lee
 */
@SuppressWarnings("serial")
public class DemoWizardChooser extends JCenteringDialog {

	DemoWizardManager manager;

	/** Creates new form DemoWizardChooser */
	public DemoWizardChooser(java.awt.Frame parent, DemoWizardManager manager) {
		super(parent, false);

		this.manager = manager;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		eastPanel = new javax.swing.JPanel();
		buttonPanel = new javax.swing.JPanel();
		runButton = new javax.swing.JButton();
		loadButton = new javax.swing.JButton();
		aboutButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		titleLabel = new javax.swing.JLabel();
		scroller = new javax.swing.JScrollPane();
		jlist = new javax.swing.JList();

		setTitle("Wizards");
		setModal(true);
		buttonPanel.setLayout(new java.awt.GridLayout(4, 1));

		runButton.setText("Run Wizard");
		runButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				runButtonActionPerformed(evt);
			}
		});

		buttonPanel.add(runButton);

		loadButton.setText("Load Wizard");
		loadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loadButtonActionPerformed(evt);
			}
		});

		buttonPanel.add(loadButton);

		aboutButton.setText("About Wizard");
		aboutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutButtonActionPerformed(evt);
			}
		});

		buttonPanel.add(aboutButton);

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		buttonPanel.add(cancelButton);

		eastPanel.add(buttonPanel);

		getContentPane().add(eastPanel, java.awt.BorderLayout.EAST);

		titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLabel.setText("Please choose the wizard to run.");
		getContentPane().add(titleLabel, java.awt.BorderLayout.NORTH);

		jlist.setModel(manager);
		jlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		scroller.setViewportView(jlist);

		getContentPane().add(scroller, java.awt.BorderLayout.CENTER);

		pack();
	}

	// </editor-fold>//GEN-END:initComponents

	private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN
		// -
		// FIRST
		// :
		// event_aboutButtonActionPerformed
		if (jlist.getSelectedIndex() == -1)
			return;
		String wizardName = (String) manager.getElementAt(jlist
				.getSelectedIndex());
		JOptionPane.showMessageDialog(this, manager
				.getDescriptionFor(wizardName), "About " + wizardName,
				JOptionPane.INFORMATION_MESSAGE);
	}// GEN-LAST:event_aboutButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN
		// -
		// FIRST
		// :
		// event_cancelButtonActionPerformed
		setVisible(false);
	}// GEN-LAST:event_cancelButtonActionPerformed

	private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN
		// -
		// FIRST
		// :
		// event_loadButtonActionPerformed
		manager.getEditor().loadNewWizard();
	}// GEN-LAST:event_loadButtonActionPerformed

	private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-
		// FIRST
		// :
		// event_runButtonActionPerformed
		if (jlist.getSelectedIndex() == -1)
			return;
		setVisible(false);
		manager.runWizard((String) manager.getElementAt(jlist
				.getSelectedIndex()));
	}// GEN-LAST:event_runButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton aboutButton;
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JButton cancelButton;
	private javax.swing.JPanel eastPanel;
	private javax.swing.JList jlist;
	private javax.swing.JButton loadButton;
	private javax.swing.JButton runButton;
	private javax.swing.JScrollPane scroller;
	private javax.swing.JLabel titleLabel;
	// End of variables declaration//GEN-END:variables

}
